### ISSUE TITLE
I can add a realm role to an user and search users by realm role

### ISSUE THREAD

**Issue by HeffeV** [jidoka-be/jdk-keycloak-admin#19]
I can add a realm role to an user and search users by realm role

**Comment by bastijns-jeroen** [comment]
This will not get merged for the following reasons:
- searchUsersByRealmRole can only return users for which the realm role is directly assigned to the user, which defeats the purpose we had for this.
- addRealmRoleToUser is not very useful as users are mostly added to groups which contain the realm roles
